player2:
  # 一个本地 app，下载地址 https://player2.game/
  type: chat
  # 目前仅支持这一种 api 类型
  api_type: openai
  url: http://127.0.0.1:4315/v1
  api_key: empty
  models:
    - default

openai:
  type: chat
  api_type: openai
  url: https://api.openai.com/v1
  api_key:
  models:
    - gpt-4o
    - chatgpt-4o-latest
    - gpt-4o-mini
    - o1
    - o1-mini
    - o3-mini
    - o1-preview

aliyun:
  type: chat
  api_type: openai
  url: https://dashscope.aliyuncs.com/compatible-mode/v1
  api_key:
  models:
    - qwen-plus
    - qwen-max
    - qwen-turbo
    - qwen-long

system:
  # 系统 TTS，虽然质量很差很差，但是好在响应速度快，而且系统自带，无需配置
  type: tts
  # 可以是 fish-audio 或者 system（调用系统 tts，只能自己听见了）
  api_type: system
  url: no_url
  api_key: empty_key
  models:
    - default

fish-audio:
  type: tts
  api_type: fish-audio
  url: https://api.fish.audio/v1
  api_key:
  models:
    - b2b2d0fa88ee44d789da28ebbd97421e # Neuro-sama （英文）
    - 4858e0be678c4449bf3a7646186edd42 # 纳西妲（英文）
    - 1aacaeb1b840436391b835fd5513f4c4 # 芙宁娜（中文）
    - ec4875ed4e154ed09d1b501a2214579a # 雷电将军（中文）
    - bcbb6d60721c44a489bc33dd59ce7cfc # 流萤（中文）
    - bca87f0aa93f4e85aee1e132ca6bd254 # 日奈（日文）
    - b85f3ec7e48b4abfaa723d95c1cdaff5 # 草薙宁宁（日文）
    - ac7df666cedb48fda3820bf404691c88 # 朝比奈真冬（日文）
    - 0b808d6e6c4a47999e50ffbbc47172c3 # 姊崎宁宁（日文）

fish-audio-cn:
  type: tts
  api_type: fish-audio
  url: https://api.fish-audio.cn/v1
  api_key:
  models:
    - b2b2d0fa88ee44d789da28ebbd97421e # Neuro-sama （英文）
    - 4858e0be678c4449bf3a7646186edd42 # 纳西妲（英文）
    - 1aacaeb1b840436391b835fd5513f4c4 # 芙宁娜（中文）
    - ec4875ed4e154ed09d1b501a2214579a # 雷电将军（中文）
    - bcbb6d60721c44a489bc33dd59ce7cfc # 流萤（中文）
    - bca87f0aa93f4e85aee1e132ca6bd254 # 日奈（日文）
    - b85f3ec7e48b4abfaa723d95c1cdaff5 # 草薙宁宁（日文）
    - ac7df666cedb48fda3820bf404691c88 # 朝比奈真冬（日文）
    - 0b808d6e6c4a47999e50ffbbc47172c3 # 姊崎宁宁（日文）